package backend;

public enum Command {
	FORWARD, BACKWARD, SUM, DIFFERENCE, PRODUCT, QUOTIENT, REMAINDER, MINUS, RANDOM, SIN,
	COS, TAN, ATAN, LOG, POW, PI, LESS, GREATER, EQUAL, NOTEQUAL, AND, OR, NOT;
}

