package slogo_team09;

public enum Command {
	FORWARD, BACK, LEFT, RIGHT, SETHEADING, TOWARDS, SETXY, SUM, DIFFERENCE, PRODUCT, QUOTIENT, REMAINDER, MINUS, RANDOM, SIN,
	COS, TAN, ATAN, LOG, POW, PI, LESS, GREATER, EQUAL, NOTEQUAL, AND, OR, NOT;
}

